// bench_apply_inmem_grow_mpi
// ==========================
// A second in-memory basis-build variant of bench_apply_mpi. Where
// bench_apply_inmem_mpi enumerates the whole constrained basis with the MPI
// work-stealing constraint-tree search, this binary builds the basis by
// *closure under the Hamiltonian* ("growing" the basis from a seed):
//
//   1. On rank 0 only, run the ordinary serial depth-first constraint-tree
//      search just long enough to collect a modest seed set of complete valid
//      ice states (>= 1000 x world_size of them). The remaining, still-
//      incomplete tree nodes left on the DFS stack are discarded -- we only
//      want a handful of guaranteed-valid states to nucleate the growth.
//   2. Scatter those seeds to their hash-owning ranks (mpi_context's
//      state->rank hash), so every rank starts with the slice of the seed it
//      will ultimately own.
//   3. Grow the basis to a fixed point, mirroring the off-diagonal apply's
//      communication pattern: each rank applies every off-diagonal term of H to
//      its frontier of owned states, routes each produced neighbour to its
//      hash-owner, and on the receiving side inserts any genuinely new state
//      into a locally-sorted set. Newly inserted states form the next round's
//      frontier. Because the ice-rule sector is connected under ring exchange,
//      repeating this until no rank discovers a new state anywhere reconstructs
//      exactly the same distributed basis the tree search would have produced.
//
// Why a std::set for the discovery structure: growth needs, per received state,
// a fast "is this already known?" test plus an insert that keeps the collection
// ordered (so the eventual hand-off to the basis vector is cheap and dedup is
// free). A balanced BST (std::set) gives O(log n) insert-if-absent with the
// states held in sorted order. Its node overhead is real, and the target bases
// are enormous (~1 TB of states globally at the extreme), so once growth is
// finished we stream the set into the plain std::vector that backs each
// Hash-MPI basis in chunks, erasing set nodes as we copy them out -- the set
// shrinks as the vector fills, rather than both being fully resident at once.
//
// The apply, timing, memory reporting, and machine-readable [result] line are
// identical to bench_apply_mpi / bench_apply_inmem_mpi so all three can be
// compared directly.

#include "argparse/argparse.hpp"
#include "hamiltonian_setup.hpp"
#include <nlohmann/json.hpp>
#include "logging.hpp"
#include "operator_mpi.hpp"
#include "common_bits_mpi.hpp"

// in-memory basis-build path
#include "admin.hpp"              // get_permutation
#include "basis_io_h5.hpp"        // basis_io::make_sector_string
#include "basis_grow_mpi.hpp"     // seed DFS + scatter + grow helpers

#include <random>
#include "timeit.hpp"
#include <fstream>
#include <iomanip>
#include <cstdlib>
#include <algorithm>
#include <omp.h>


static void print_mem(const MPIHashContext& ctx, const char* label) {
    size_t rss = rss_bytes();
    size_t rss_max = 0;
    MPI_Reduce(&rss, &rss_max, 1, get_mpi_type<size_t>(), MPI_MAX, 0, MPI_COMM_WORLD);
    size_t rss_sum = 0;
    MPI_Reduce(&rss, &rss_sum, 1, get_mpi_type<size_t>(), MPI_SUM, 0, MPI_COMM_WORLD);
    if (ctx.my_rank == 0)
        std::cout << "[mem] " << label
                  << "  max=" << rss_max / (1<<20) << " MiB"
                  << "  total=" << rss_sum / (1<<20) << " MiB\n";
}


using json = nlohmann::json;
using namespace projED;
using state_t = ZBasisBase::state_t;


int main(int argc, char* argv[]){

    argparse::ArgumentParser prog(argv[0]);
    prog.add_argument("lattice_file");
    prog.add_argument("n_spinon_pairs")
        .help("number of spinon pairs (default 0 = ground constraint sector)")
        .default_value(0)
        .scan<'i', int>();

    // ---- basis-build options ----------------------------------------------
    // Sector is REQUIRED: growth reconstructs only the H-connected closure of
    // the seeds, and ring exchange conserves the per-sublattice polarisation, so
    // an unpinned seed set samples an ill-defined union of partial sectors. See
    // basis_grow_mpi.hpp.
    prog.add_argument("-r", "--sector")
        .help("REQUIRED target global polarisation sector (one int per "
              "sublattice); growth is meaningful only within a fixed sector")
        .nargs(argparse::nargs_pattern::at_least_one)
        .required()
        .scan<'d', int>();
    prog.add_argument("--order_spins")
        .help("index ordering used to prune the seed search tree")
        .choices("none", "greedy", "random")
        .default_value(std::string{"greedy"});
    prog.add_argument("--seeds-per-rank")
        .help("target number of seed states per rank generated by the rank-0 "
              "DFS (total seeds >= this x world_size). The remaining incomplete "
              "DFS nodes are discarded.")
        .default_value(1000)
        .scan<'i', int>();
    prog.add_argument("--grow-batch")
        .help("frontier states per pipelined redistribution chunk during growth. "
              "Peak comm memory ~ 3 x this x #offdiag states; bound it at high "
              "node counts / tight RAM.")
        .default_value(1<<16)
        .scan<'i', int>();

    // ---- apply/benchmark options (mirror bench_apply_mpi) ------------------
    prog.add_argument("--seed")
        .help("Seed for the RNG")
        .scan<'i', unsigned int>()
        .default_value(0u);
    // NB: there is deliberately no trim option. The grown basis is already the
    // exact closure of the seeds under H, so remove_null_states is at best a
    // no-op; and for a Hamiltonian whose off-diagonal term list is not closed
    // under conjugation it would drop states that are still images of kept
    // states, breaking the apply.
    prog.add_argument("--basis-type")
        .help("Basis search structure: bst | interp | fast  (default: run all three)")
        .default_value(std::string("all"));
    prog.add_argument("--interp-bits")
        .help("For interp basis: high bits of uint64[1] used as bounds-map key (1-64, default 64).")
        .default_value(64)
        .scan<'i', int>();
    prog.add_argument("--repeats")
        .help("Number of timed apply repetitions. With N>1 the first repeat is "
              "treated as warm-up and excluded from the min/avg summary.")
        .default_value(1)
        .scan<'i', int>();
    prog.add_argument("--threads")
        .help("OpenMP threads per rank for the apply (0 = leave runtime default).")
        .default_value(0)
        .scan<'i', int>();
    prog.add_argument("--verbosity")
        .help("Level of detail to print")
        .default_value(2)
        .scan<'i', int>();
    prog.add_argument("--all-rank-info")
        .help("Prints stats for all ranks (default: only rank 0)")
        .default_value(false)
        .implicit_value(true);
    prog.add_argument("--strategy")
        .help("Choice of apply kernel")
        .choices("prealloc", "pipe", "pipe_plain", "prealloc_p2p")
        .default_value("pipe");

    try {
        prog.parse_args(argc, argv);
    } catch (const std::runtime_error& err) {
        std::cerr << err.what() << "\n";
        std::cerr << prog;
        return 1;
    }

    auto bt = prog.get<std::string>("--basis-type");
    if (bt != "all" && bt != "bst" && bt != "interp" && bt != "fast") {
        std::cerr << "Invalid --basis-type '" << bt << "'. Must be one of: bst, interp, fast, all\n";
        std::cerr << prog;
        return 1;
    }

    int interp_bits = prog.get<int>("--interp-bits");
    if (interp_bits < 1 || interp_bits > 64) {
        std::cerr << "--interp-bits must be between 1 and 64\n";
        return 1;
    }
    uint64_t interp_hi_mask = (interp_bits >= 64) ? ~0ULL : (~0ULL << (64 - interp_bits));

    unsigned int seed = prog.get<unsigned int>("--seed");
    int repeats = std::max(1, prog.get<int>("--repeats"));

    int threads = prog.get<int>("--threads");
    if (threads > 0) omp_set_num_threads(threads);

    // Threads call MPI only between parallel regions, so FUNNELED suffices.
    int provided = 0;
    MPI_Init_thread(NULL, NULL, MPI_THREAD_FUNNELED, &provided);
    if (provided < MPI_THREAD_FUNNELED) {
        std::cerr << "Warning: MPI provides thread level " << provided
                  << " < FUNNELED; hybrid runs may be unsafe\n";
    }

    // Step 1: Load ring data from JSON
    auto lattice_file = prog.get<std::string>("lattice_file");
    std::ifstream jfile(lattice_file);
    if (!jfile) {
        std::cerr << "Failed to open JSON file\n";
        return 1;
    }
    json jdata;
    jfile >> jdata;

    MPIHashContext ctx;
    logging::configure(ctx.my_rank, prog.get<int>("--verbosity"), prog.get<bool>("--all-rank-info"));

    using T=double;
    SymbolicOpSum<T> H_sym;

    // Purely off-diagonal Hamiltonian (ring exchange only; no Ising/field
    // diagonal). The diagonal pass is trivial, so the timed apply is entirely
    // the searched off-diagonal path -- same choice as bench_apply_mpi. It is
    // also exactly the edge set the growth phase closes over.
    std::vector<double> gv {1.0, -0.2, -0.2, -0.2};
    build_hamiltonian(H_sym, jdata, gv);

    MPILazyOpSumStrategy strat = parse_mpi_strategy(prog.get<std::string>("--strategy"));

    auto env_int = [](const char* name, int def) {
        const char* e = std::getenv(name);
        return e ? std::atoi(e) : def;
    };
    const int search_group = std::min(32, std::max(1, env_int("APPLY_SEARCH_GROUP", 8)));
    const int scatter_pd   = std::max(0, env_int("APPLY_SCATTER_PD", 16));

    // ------------------------------------------------------------------------
    // Step 2: build the basis by growth (seed DFS -> scatter -> Hamiltonian
    // closure), directly into RAM (no disk). The lattice is permuted only to
    // prune the seed DFS tree; seeds are un-permuted before use, so H_sym (built
    // from the un-permuted JSON above) stays valid.
    // ------------------------------------------------------------------------
    lattice lat(jdata);
    auto choice = prog.get<std::string>("--order_spins");
    std::vector<size_t> perm = get_permutation(choice, lat);
    MPI_Bcast(perm.data(), perm.size(), get_mpi_type<size_t>(), 0, MPI_COMM_WORLD);
    lat.apply_permutation(perm);

    int num_spinon_pairs = prog.get<int>("n_spinon_pairs");
    auto target_sector = prog.get<std::vector<int>>("--sector");
    size_t seeds_per_rank = static_cast<size_t>(std::max(1, prog.get<int>("--seeds-per-rank")));
    size_t seed_target = seeds_per_rank * static_cast<size_t>(ctx.world_size);
    size_t grow_batch = static_cast<size_t>(std::max(1, prog.get<int>("--grow-batch")));

    if (ctx.my_rank == 0)
        std::cout << "[build] growing basis in-memory (sector="
                  << basis_io::make_sector_string(target_sector)
                  << ", seed target=" << seed_target << ") ...\n";

    print_mem(ctx, "before seed DFS");

    // Seed DFS (rank 0) -> hash-scatter -> grow to the Hamiltonian-closure fixed
    // point. The grown structure is already the sorted owned slice. See
    // basis_grow_mpi.hpp.
    double t_build0 = MPI_Wtime();
    size_t raw_local = 0, raw_global = 0, n_rounds = 0;
    std::vector<state_t> found = basis_grow::build_grown_basis_local(
            lat, num_spinon_pairs, perm, target_sector, H_sym, ctx,
            seeds_per_rank, grow_batch, raw_local, raw_global, n_rounds);

    double t_build = MPI_Wtime() - t_build0, t_build_max = 0;
    MPI_Reduce(&t_build, &t_build_max, 1, MPI_DOUBLE, MPI_MAX, 0, MPI_COMM_WORLD);
    if (ctx.my_rank == 0)
        std::cout << "[build] growth converged in " << n_rounds << " rounds, "
                  << t_build_max << " s; raw basis dim=" << raw_global << "\n";
    print_mem(ctx, "after grow (states in vector)");

    // bench_one: adopt the given state slab into the basis structure, trim,
    // redistribute (which also sorts and rebuilds the search structures), then
    // time the apply. Structured identically to bench_apply_inmem_mpi::bench_one.
    auto bench_one = [&](auto& basis, const char* tag, std::vector<state_t>&& slab) {
        if constexpr (std::is_base_of_v<ZBasisInterp, std::decay_t<decltype(basis)>>) {
            basis.set_hi_mask(interp_hi_mask);
            if (ctx.my_rank == 0)
                std::cout << "[" << tag << "] hi_mask=0x" << std::hex << interp_hi_mask
                          << std::dec << " (" << interp_bits << " bits, max "
                          << (1ULL << std::min(interp_bits, 20)) << (interp_bits > 20 ? "..." : "")
                          << " entries)\n";
        }
        print_mem(ctx, (std::string(tag) + " before adopt").c_str());
        basis.adopt_states(std::move(slab));
        // No trim: the grown basis is already the exact H-closure of the seeds.
        print_mem(ctx, (std::string(tag) + " after adopt").c_str());

        TIMEIT((std::string("[") + tag + "] redistribute").c_str(), basis.redistribute();)
        print_mem(ctx, (std::string(tag) + " after redistribute").c_str());

        if (ctx.my_rank == 0)
            std::cout << "[" << tag << "] global basis dim=" << basis.global_dim()
                      << "\n";

        // Per-rank working-set report. The searched working set (sorted states +
        // any acceleration structure) is what must exceed L3 for this benchmark
        // to exercise the DRAM-latency regime rather than a cache-resident toy.
        size_t states_bytes = basis.dim() * sizeof(ZBasisBase::state_t);
        size_t accel_bytes = 0;
        if constexpr (std::is_base_of_v<ZBasisInterp, std::decay_t<decltype(basis)>>)
            accel_bytes = basis.n_bounds_entries() * 56;
        size_t wset_local = states_bytes + accel_bytes;
        size_t wset_max = 0;
        MPI_Reduce(&wset_local, &wset_max, 1, get_mpi_type<size_t>(), MPI_MAX,
                   0, MPI_COMM_WORLD);
        if (ctx.my_rank == 0)
            std::cout << "[" << tag << "] local dim=" << basis.dim()
                      << "  states=" << states_bytes / (1<<20) << " MiB";
        if constexpr (std::is_base_of_v<ZBasisInterp, std::decay_t<decltype(basis)>>) {
            size_t nb = basis.n_bounds_entries();
            if (ctx.my_rank == 0)
                std::cout << "  bounds_entries=" << nb
                          << " (~" << nb * 56 / (1<<20) << " MiB)";
        }
        if (ctx.my_rank == 0) std::cout << "\n";

        auto H = MPILazyOpSum(basis, H_sym, ctx, strat);

        std::vector<double> v(basis.dim()), u(basis.dim(), 0.0);
        std::mt19937 rng(seed);
        projED::set_random_unit_mpi(v, rng);
        print_mem(ctx, (std::string(tag) + " before apply (vecs allocated)").c_str());

        // Per-repeat wall time = slowest rank (barrier-synchronised entry).
        double t_min = 0, t_sum = 0;
        int n_counted = 0;
        for (int rep = 0; rep < repeats; rep++) {
            std::fill(u.begin(), u.end(), 0.0);
            if (ctx.my_rank == 0)
                std::cout << "[" << tag << "] u += Av rep " << rep << ": ";
            MPI_Barrier(MPI_COMM_WORLD);
            double t0 = MPI_Wtime();
            H.evaluate_add(v.data(), u.data());
            double dt = MPI_Wtime() - t0, dt_max = 0;
            MPI_Reduce(&dt, &dt_max, 1, MPI_DOUBLE, MPI_MAX, 0, MPI_COMM_WORLD);

            bool warmup = (repeats > 1 && rep == 0);
            if (ctx.my_rank == 0)
                std::cout << dt_max * 1e3 << " ms" << (warmup ? " (warm-up)" : "") << "\n";

            if (!warmup) {
                t_min = (n_counted == 0) ? dt_max : std::min(t_min, dt_max);
                t_sum += dt_max;
                n_counted++;
            }
        }
        if (ctx.my_rank == 0 && n_counted > 1)
            std::cout << "[" << tag << "] u += Av summary over " << n_counted
                      << " repeats: min=" << t_min * 1e3
                      << " ms  avg=" << t_sum / n_counted * 1e3 << " ms\n";

        // Global checksum of u so different strategies can be cross-checked.
        double loc_sum = 0.0, loc_sq = 0.0;
        for (ZBasisBase::idx_t i = 0; i < basis.dim(); ++i) {
            loc_sum += u[i];
            loc_sq  += u[i] * u[i];
        }
        double glob_sum = 0.0, glob_sq = 0.0;
        MPI_Reduce(&loc_sum, &glob_sum, 1, MPI_DOUBLE, MPI_SUM, 0, MPI_COMM_WORLD);
        MPI_Reduce(&loc_sq,  &glob_sq,  1, MPI_DOUBLE, MPI_SUM, 0, MPI_COMM_WORLD);

        if (ctx.my_rank == 0 && n_counted >= 1) {
            std::cout << "[result]"
                      << " tag=" << tag
                      << " strategy=" << strat
                      << " ranks=" << ctx.world_size
                      << " threads=" << omp_get_max_threads()
                      << " search_group=" << search_group
                      << " scatter_pd=" << scatter_pd
                      << " global_dim=" << basis.global_dim()
                      << " wset_kib=" << wset_max / 1024
                      << " repeats=" << n_counted
                      << " min_ms=" << t_min * 1e3
                      << " avg_ms=" << t_sum / n_counted * 1e3
                      << " sum=" << std::setprecision(12) << glob_sum
                      << " sumsq=" << std::setprecision(12) << glob_sq
                      << "\n";
        }
        print_mem(ctx, (std::string(tag) + " after apply").c_str());
    };

    // Requested basis structures. All but the last adopt a copy of the found
    // states; the last moves them (so the common single-type run never doubles
    // the state footprint). The redistribute() inside bench_one frees the slab.
    std::vector<std::string> types;
    if (bt == "all" || bt == "bst")    types.push_back("bst");
    if (bt == "all" || bt == "interp") types.push_back("interp");
    if (bt == "all" || bt == "fast")   types.push_back("fast");

    for (size_t ti = 0; ti < types.size(); ++ti) {
        const bool last = (ti + 1 == types.size());
        std::vector<state_t> slab = last ? std::move(found)
                                          : std::vector<state_t>(found);
        if (types[ti] == "bst")    { ZBasisBST_HashMPI     b; bench_one(b, "BST",    std::move(slab)); }
        if (types[ti] == "interp") { ZBasisInterp_HashMPI  b; bench_one(b, "interp", std::move(slab)); }
        if (types[ti] == "fast")   { ZBasisBSTFast_HashMPI b; bench_one(b, "fast",   std::move(slab)); }
    }

    MPI_Finalize();
    return 0;
}
