#include <argparse/argparse.hpp>

#include <nlohmann/json.hpp>
#include <fstream>
#include <filesystem>
#include <mpi.h>

#include "admin.hpp"               // get_permutation
#include "basis_grow_mpi.hpp"      // seed DFS + scatter + grow + drain helpers
#include "physics/geometry.hpp"

#include "hamiltonian_setup.hpp"
#include "operator_mpi.hpp"
#include "lanczos_mpi.hpp"
#include "lanczos_cli.hpp"
#include "logging_cli.hpp"
#include "expectation_eval.hpp"

using json = nlohmann::json;
using namespace projED;
using basis_t = ZBasisBSTFast_HashMPI;

// Grow-by-closure counterpart of diag_DOQSI_fused_mpi: builds the basis, in RAM
// and without ever touching disk, by *growing* it from a small seed instead of
// enumerating the whole constrained manifold with the work-stealing tree search.
// Per rank:
//   i)   rank 0 runs the plain serial DFS just long enough to collect a seed set
//        (>= --seeds-per-rank x world_size complete valid ice states within the
//        fixed --sector); the seeds are hash-scattered to their owning ranks and
//        the basis is grown to the Hamiltonian-closure fixed point (each round
//        applies H to the frontier, routes neighbours to their hash owner, and
//        inserts new states into a per-rank sorted set). See basis_grow_mpi.hpp;
//   ii)  the discovery set is streamed into the basis vector and redistributed;
//   iii) the checkpointed Lanczos recurrence runs and eigenpairs + ring
//        observables are written to HDF5.
//
// --sector is REQUIRED: growth reconstructs only the H-connected closure of the
// seeds, and ring exchange conserves the per-sublattice polarisation, so an
// unpinned seed set would sample an ill-defined union of partial sectors. No
// trimming is done: the grown basis is already the exact closure (trimming would
// be a no-op at best, and for a Hamiltonian whose off-diagonal term list is not
// closed under conjugation it would drop states that are still images of kept
// states and break the apply).

int main(int argc, char* argv[]) {
	argparse::ArgumentParser prog(argv[0]);
	prog.add_argument("lattice_file")
		.help("The json-valued lattice spec");
	prog.add_argument("n_spinon_pairs")
		.default_value(0)
		.scan<'i', int>();
    // REQUIRED: growth is only meaningful within a fixed conserved sector.
    prog.add_argument("--sector", "-r")
        .help("REQUIRED target global polarisation sector (one int per "
              "sublattice); growth is meaningful only within a fixed sector")
        .nargs(argparse::nargs_pattern::at_least_one)
        .required()
        .scan<'d', int>();
	prog.add_argument("--order_spins")
		.help("index ordering used to prune the seed search tree")
		.choices("none", "greedy", "random")
		.default_value(std::string{"greedy"});

    // grow tuning
    prog.add_argument("--seeds-per-rank")
        .help("target number of seed states per rank generated by the rank-0 "
              "DFS (total seeds >= this x world_size). The remaining incomplete "
              "DFS nodes are discarded.")
        .default_value(1000)
        .scan<'i', int>();
    prog.add_argument("--drain-chunk")
        .help("states copied per chunk when streaming the discovery set into the "
              "basis vector (larger = fewer iterations, same peak).")
        .default_value(1<<20)
        .scan<'i', int>();
    prog.add_argument("--grow-batch")
        .help("frontier states per pipelined redistribution chunk during growth. "
              "Peak comm memory ~ 3 x this x #offdiag states, so bound it at high "
              "node counts / tight RAM (smaller = more, smaller collective rounds).")
        .default_value(1<<16)
        .scan<'i', int>();

    // G specification
    {
        auto &group = prog.add_mutually_exclusive_group(true);
        group.add_argument("--B")
            .help("magnetic field, units of Jzz")
            .nargs(3)
            .scan<'g', double>();

        group.add_argument("--g")
            .help("raw ring exchange, units of Jzz")
            .nargs(4)
            .scan<'g', double>();

        prog.add_argument("--Jpm")
            .help("Jpm, units of Jzz")
            .scan<'g', double>();
    }

    prog.add_argument("-o", "--output_dir")
        .required()
        .help("output directory ");

    provide_lanczos_options(prog);
    provide_logging_options(prog);

    try {
        prog.parse_args(argc, argv);
    } catch (const std::exception& err){
		std::cerr << err.what() << std::endl;
		std::cerr << prog;
        std::exit(1);
    }

    MPI_Init(&argc, &argv);

	// Step 1: Load ring data from JSON
    auto lattice_file = prog.get<std::string>("lattice_file");
	std::ifstream jfile(lattice_file);
	if (!jfile) {
		std::cerr << "Failed to open JSON file\n";
		return 1;
	}
	json jdata;
	jfile >> jdata;

    MPIctx ctx;
    configure_logging(prog, ctx.my_rank);

	using coeff_t=double;
    bool calc_partial_vol = true;

	SymbolicOpSum<coeff_t> H_sym;

    char outfilename_buf[1024];

    std::stringstream s;

    if (prog.is_used("--g")){
        auto gv = prog.get<std::vector<double>>("--g");
        build_hamiltonian(H_sym, jdata, gv);

        snprintf(outfilename_buf, 1024, "g0=%.4f%%g1=%.4f%%g2=%.4f%%g3=%.4f%%",
                gv[0], gv[1], gv[2],gv[3]);
    } else {
        auto Jpm = prog.get<double>("--Jpm");
        auto Bv = prog.get<std::vector<double>>("B");

        Eigen::Vector3d B;
        for (size_t i=0; i<3; i++)
            B[i] = Bv[i];

        snprintf(outfilename_buf, 1024, "Jpm=%.4f%%Bx=%.4f%%By=%.4f%%Bz=%.4f%%",
                Jpm, B[0], B[1], B[2]);

        build_hamiltonian(H_sym, jdata, Jpm, B, ctx.my_rank != 0);
    }

    // make the out dir if not exists
    std::filesystem::create_directories(prog.get<std::string>("--output_dir"));

    s << prog.get<std::string>("--output_dir") << "/" << outfilename_buf;

	// Step 2: build the basis by growth, directly into RAM (no disk).
	lattice lat(jdata);

	auto choice = prog.get<std::string>("--order_spins");

	// Permute the indices to make early seed-tree truncation as efficient as
	// possible; seeds are unpermuted as they are emitted. Every rank must use
	// the same ordering, so rank 0's choice is broadcast.
	std::vector<size_t> perm = get_permutation(choice, lat);
	MPI_Bcast(perm.data(), perm.size(), get_mpi_type<size_t>(), 0, MPI_COMM_WORLD);
	lat.apply_permutation(perm);

    auto num_spinon_pairs = prog.get<int>("n_spinon_pairs");
    auto target_sector = prog.get<std::vector<int>>("--sector");
    size_t seeds_per_rank = static_cast<size_t>(std::max(1, prog.get<int>("--seeds-per-rank")));
    size_t drain_chunk = static_cast<size_t>(std::max(1, prog.get<int>("--drain-chunk")));
    size_t grow_batch = static_cast<size_t>(std::max(1, prog.get<int>("--grow-batch")));

    if (ctx.my_rank == 0)
        logging::log(logging::INFO) << "[Grow] Building basis in-memory by closure "
            "(sector=" << basis_io::make_sector_string(target_sector)
            << ", seeds/rank=" << seeds_per_rank << ") ...\n";

    // Seed DFS (rank 0) -> hash-scatter -> grow to the Hamiltonian-closure fixed
    // point -> stream the discovery set into a plain vector.
    size_t raw_local = 0, raw_global = 0, n_rounds = 0;
    std::vector<Uint128> found = basis_grow::build_grown_basis_local(
            lat, num_spinon_pairs, perm, target_sector, H_sym, ctx,
            seeds_per_rank, drain_chunk, grow_batch, raw_local, raw_global, n_rounds);

    if (ctx.my_rank == 0) {
        logging::log(logging::INFO) << "[Grow] Done! growth converged in "
            << n_rounds << " rounds; raw basis dim=" << raw_global << "\n";
    }

	// Step 3: adopt the grown states and hash-redistribute to the owning ranks
	// (which also sorts and rebuilds the search structures). No trim: the grown
	// basis is already the exact H-closure.
    basis_t basis;
    basis.adopt_states(std::move(found));
    basis.redistribute();
    logging::log(logging::DEBUG)<<"[MPI_BST]  Done! local basis dim="<<basis.dim()<<std::endl;
    if (ctx.my_rank == 0) {
        logging::log(logging::INFO) << "[MPI_BST] global basis dim=" << basis.global_dim()
                  << "\n";
    }

    // Estimate the steady-state RAM of the diagonalisation before committing to
    // it, summed over ranks. Three contributions dominate:
    //   (i)   the Uint128 basis states themselves;
    //   (ii)  the three length-dim double vectors the Lanczos eigenvector pass
    //         keeps live simultaneously (current v = local_v0, the scratch/
    //         previous vector u inside the iterator, and the accumulated
    //         eigenvector); the eigenvalue-only pass peaks at two of these;
    //   (iii) the operator apply plan's index cache, which stores one uint32
    //         local target index per off-diagonal nonzero (~4 B each). We count
    //         the local nonvanishing off-diagonal records exactly here (one
    //         applyState pass, cheap next to Lanczos); this is an upper bound on
    //         the plan, since records whose target is not in the basis are
    //         dropped when the plan is built.
    {
        const size_t local_dim = basis.dim();
        size_t local_offdiag_nnz = 0;
        for (size_t i = 0; i < local_dim; ++i) {
            for (const auto& [c, op] : H_sym.off_diag_terms) {
                (void)c;
                Uint128 st = basis[i];
                if (op.applyState(st) != 0) ++local_offdiag_nnz;
            }
        }

        size_t local[3] = {
            local_dim * sizeof(Uint128),          // (i)   basis states
            3 * local_dim * sizeof(double),       // (ii)  Lanczos vectors
            local_offdiag_nnz * sizeof(uint32_t), // (iii) operator index cache
        };
        size_t g[3] = {0, 0, 0};
        MPI_Allreduce(local, g, 3, get_mpi_type<size_t>(), MPI_SUM, MPI_COMM_WORLD);

        if (ctx.my_rank == 0) {
            const double MiB = 1.0 / (1 << 20);
            logging::log(logging::INFO) << "[Grow] Estimated steady-state memory (global):\n"
                      << "    basis (Uint128)        : " << g[0] * MiB << " MiB\n"
                      << "    Lanczos vectors (3x)   : " << g[1] * MiB << " MiB\n"
                      << "    total persistent       : "
                      << (g[0] + g[1] ) * MiB << " MiB\n"
                      << "    operator indices       : " << g[2] * MiB << " MiB (~4 B x off-diag nonzeros, not cached)\n" ;
        }
    }

    ////////////////////////////////////////
    // Do the diagonalisation
    lanczos_mpi::Settings settings(ctx);
    parse_lanczos_settings(prog, settings);
    settings.verbosity = prog.get<int>("--verbosity");
    settings.calc_eigenvector = true;

    double eigval;
    std::vector<double> local_v0(basis.dim());
    std::vector<double> evector;
    std::vector<double> alphas, betas;

    // Scope the Hamiltonian so its pipelined comm buffers are freed before the
    // observable phase.
    {
        auto H = MPILazyOpSum(basis, H_sym, ctx, MPILazyOpSumStrategy::PIPE);

        RealApplyFn evadd = [&H](const coeff_t* x_local, coeff_t* y_local){
            H.evaluate_add(x_local, y_local);
        };

        logging::log(logging::INFO) << "[Lanczos] finding lowest eigenvalue\n";
        auto res=  lanczos_mpi::lanczos_iterate(evadd, local_v0, alphas, betas, settings);

        logging::log(logging::DEBUG)<<"[rank "<<ctx.my_rank<<"] "<<res;

        // If we hit checkpoint and exited early, clean exit
        if (!res.eigval_converged) {
            if (ctx.my_rank == 0) {
                logging::log(logging::INFO) << "[Main] Exited initial iteration at n="<<
                    res.n_iterations<<" due to time limit. Restart to continue.\n";
            }
            MPI_Finalize();
            return 0; // Clean exit for restart
        }

        // If converged, compute final eigenvalue and eigenvector
        logging::log(logging::INFO) << "[Lanczos] tridiagonalising in Krylov space\n";
        std::vector<double> ritz;
        {
            std::vector tmp_alphas(alphas);
            std::vector tmp_betas(betas);
            tridiagonalise_one(tmp_alphas, tmp_betas, eigval, ritz);
        }

        logging::log(logging::INFO) << "[Lanczos] iterating to determine eigenvector\n";
        evector.resize(basis.dim());

        // Second pass for eigenvector
        res = lanczos_mpi::lanczos_iterate(
            evadd, local_v0, alphas, betas, settings,
            &ritz, &evector
        );
        // The ground state is accumulated into evector; local_v0 holds the
        // (now unneeded) final Lanczos vector and is recycled as a scratch
        // buffer in the observable phase below.

        // If we hit checkpoint and exited early (eigenvector not fully
        // reconstructed), clean exit
        if (!res.eigvec_converged) {
            if (ctx.my_rank == 0) {
            logging::log(logging::INFO) << "[Main] Exited second iteration at n="<<
                res.n_iterations<<" due to time limit. Restart to continue.\n";
            }
            MPI_Finalize();
            return 0; // Clean exit for restart
        }
    } // H freed here


    std::string out_filename = std::filesystem::path(s.str()+".eigs.h5")
        .replace_extension(".out.h5");

    if (ctx.my_rank == 0){
        logging::log(logging::INFO) << "Eigenvalues:\n" << eigval << "\n\n";
        logging::log(logging::INFO) << "Writing to\n"<<out_filename<<std::endl;
    }

    // dummy (here in case we calc more later
    std::vector<double> eigvals{eigval};

    // Step 4: evaluate the ring observables (matrix free) in the ground
    // state |psi> = evector
    auto [ringL, ringR, sl_list]  = get_ring_ops(jdata);

    int n_operators = ringL.size();
    std::vector<double> expect_O(n_operators); // < O >
    std::vector<double> expect_O_O(n_operators); // < O_0' O_j >
    std::vector<double> expect_F(n_operators); // < O'_j O_j >
    std::array<std::vector<double>, 4> partial_vol; // < O O O > around missing plaq

    {
        if (ctx.my_rank == 0)
            logging::log(logging::INFO)<<"Compute <O> and <OO>... "<<std::flush;

        std::vector<double> chi(basis.dim()); // |chi> = O_j |psi>
        std::vector<double>& u = local_v0;    // recycled: |u> = O_0 |psi>

        for (int opi=0; opi<n_operators; opi++){
            if (ctx.my_rank == 0) logging::log(logging::INFO)<<opi<<" " <<std::flush;
            // Constructed per iteration so each operator's comm buffers are
            // freed again before the next one.
            MPILazyOpSum<double, basis_t> op(basis, ringL[opi], ctx);
            op.evaluate(evector.data(), chi.data());
            if (opi == 0){
                u = chi; // copies into the existing buffer, no new allocation
            }
            double res_local = projED::inner(chi, evector);
            double res;
            MPI_Reduce(&res_local, &res, 1, MPI_DOUBLE, MPI_SUM, 0, MPI_COMM_WORLD);
            // res now contains full total <O psi | psi>
            if (ctx.my_rank == 0){
                expect_O[opi] = res;
            }

            // < psi | O_0' O_j | psi > == <u | chi >
            res_local = projED::inner(u, chi);
            MPI_Reduce(&res_local, &res, 1, MPI_DOUBLE, MPI_SUM, 0, MPI_COMM_WORLD);
            // res now contains full total <O_0 psi | O_j psi>
            if (ctx.my_rank == 0){
                expect_O_O[opi] = res;
            }

            // Flippability === <chi | chi> == <psi | O_j' O_j |psi>
            res_local = projED::inner(chi, chi);
            MPI_Reduce(&res_local, &res, 1, MPI_DOUBLE, MPI_SUM, 0, MPI_COMM_WORLD);
            if (ctx.my_rank == 0){
                expect_F[opi] = res;
            }
        }

        // partial volume operators
        if (calc_partial_vol){
            if (ctx.my_rank == 0) logging::log(logging::INFO)<<"Compute <OOO>... "<<std::flush;
            // computing expectation values of the incomplete volumes
            for (int sl=0; sl<4; sl++){
                auto par_vol_operators = get_partial_vol_ops(jdata, ringL, sl);
                partial_vol[sl].resize(par_vol_operators.size(), 0.0);
                for (size_t opi=0; opi<par_vol_operators.size(); opi++){
                    if (ctx.my_rank == 0) logging::log(logging::INFO)<<opi<<" "<<std::flush;
                    // Per-iteration construction, as in the ring loop.
                    MPILazyOpSum<double, basis_t> op(basis, par_vol_operators[opi], ctx);
                    op.evaluate(evector.data(), chi.data());
                    double res = 0;
                    double res_local = projED::inner(chi, evector);
                    MPI_Reduce(&res_local, &res, 1, MPI_DOUBLE, MPI_SUM, 0, MPI_COMM_WORLD);
                    // res contains the goods (root only)
                    if (ctx.my_rank == 0){
                        partial_vol[sl][opi] = res;
                    }
                }
            }

            if (ctx.my_rank == 0)
                logging::log(logging::INFO)<<"\nCompute <OOO> complete "<<std::endl;
        }


    }



    if (ctx.my_rank == 0){
        hid_t out_fid =
            H5Fcreate(out_filename.c_str(),
                    H5F_ACC_TRUNC, H5P_DEFAULT, H5P_DEFAULT);
        if (out_fid < 0)
            throw std::runtime_error("Failed to create HDF5 file");
        logging::log(logging::INFO) << "Done!" << std::endl;

        // write out the data
        write_string_to_hdf5(out_fid, "latfile_json", lattice_file);

        std::string sector_str = basis_io::make_sector_string(target_sector);

        write_string_to_hdf5(out_fid, "sector", sector_str);

        write_expectation_vals_h5(out_fid, "ring", expect_O, ringL.size(), 1);
        write_expectation_vals_h5(out_fid, "flippability", expect_F, ringL.size(), 1);
        write_expectation_vals_h5(out_fid, "ring_2", expect_O_O, ringL.size(), 1);

        hsize_t dims[1]={1};
        write_dataset(out_fid, "eigenvalues", eigvals.data(), dims, 1);


        if (calc_partial_vol){
            // save the incomplete vol operators (each sl)
            for (size_t sl = 0; sl < partial_vol.size(); ++sl) {
                const auto& vec = partial_vol[sl];
                std::string name = "partial_vol_sl" + std::to_string(sl);
                write_expectation_vals_h5(out_fid, name.c_str(), vec, vec.size(), 1);
            }
        }

        H5Fclose(out_fid);
    }


    MPI_Finalize();

	return 0;
}
